### ISSUE TITLE
Visual eyetracker at night and NVG

### ISSUE THREAD

**Issue by kgalguften** [mbucchia/Varjo-Foveated#2]
Hi
First of all, thanks for your work and outstanding contribution with the foveated rendering for DCS. I can see the eye tracker box at night, at bit annoying. But with NVG the whole box is clearly visible with a hole in the middle. Is it possible to adjust the setting to fade this out?

Thanks
Karl

**Comment by mbucchia** [comment]
Hi, this is a game bug, nothing I can do unfortunately. I do here there is a mod to prevent this issue, though I haven't tried it myself:

https://www.digitalcombatsimulator.com/en/files/3321955/

**Comment by kgalguften** [comment]
Ok, I will. Thanks for your support. I’ll try the mod.

**Comment by mbucchia** [comment]
The NVG bug was fixed in DCS 2.9.
